version: '3.8'

services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        volumes:
            - ../:/var/www
        networks:
            - laravel-net

    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-net

networks:
    laravel-net:
